# We're using the "admin" user because it works with the default container config out of the box, and this isn't an
# exercise in configuring IBM MQ.
ibm:
  mq:
    host: localhost
    port: 1414
    queue-manager: QM1
    queue: DEV.QUEUE.1
    channel: DEV.ADMIN.SVRCONN
    username: admin
    password: passw0rd
    receive-timeout: 2000

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"